CREATE TABLE task(
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title VARCHAR(20) NOT NULL,
    description TEXT
);

CREATE TABLE task_list(
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title VARCHAR(20) NOT NULL
);

CREATE TABLE task_list_task(
    task_list_id INT,
    task_id INT,
    PRIMARY KEY (task_list_id, task_id),
    CONSTRAINT fk_task_list FOREIGN KEY (task_list_id) REFERENCES task_list(id) ON DELETE CASCADE,
    CONSTRAINT fk_task FOREIGN KEY (task_id) REFERENCES task(id) ON DELETE CASCADE
);