service: aws-node-koa-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  task:
    handler: task.handler
    events:
      - httpApi: '*'
        
  tasklist:
    handler: task-list.handler
    events:
      - httpApi: '*'